/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as MocksRouteImport } from './routes/mocks'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as PracticeTestIdRouteImport } from './routes/practice.$testId'
import { Route as MocksMockIdRouteImport } from './routes/mocks.$mockId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const MocksRoute = MocksRouteImport.update({
  id: '/mocks',
  path: '/mocks',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTestIdRoute = PracticeTestIdRouteImport.update({
  id: '/$testId',
  path: '/$testId',
  getParentRoute: () => PracticeRoute,
} as any)
const MocksMockIdRoute = MocksMockIdRouteImport.update({
  id: '/$mockId',
  path: '/$mockId',
  getParentRoute: () => MocksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mocks': typeof MocksRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mocks/$mockId': typeof MocksMockIdRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mocks': typeof MocksRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mocks/$mockId': typeof MocksMockIdRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/leaderboard': typeof LeaderboardRoute
  '/mocks': typeof MocksRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/mocks/$mockId': typeof MocksMockIdRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/mocks'
    | '/practice'
    | '/resources'
    | '/sitemap.xml'
    | '/mocks/$mockId'
    | '/practice/$testId'
    | '/results/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/mocks'
    | '/practice'
    | '/resources'
    | '/sitemap.xml'
    | '/mocks/$mockId'
    | '/practice/$testId'
    | '/results/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/leaderboard'
    | '/mocks'
    | '/practice'
    | '/resources'
    | '/sitemap.xml'
    | '/mocks/$mockId'
    | '/practice/$testId'
    | '/results/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MocksRoute: typeof MocksRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mocks': {
      id: '/mocks'
      path: '/mocks'
      fullPath: '/mocks'
      preLoaderRoute: typeof MocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$testId': {
      id: '/practice/$testId'
      path: '/$testId'
      fullPath: '/practice/$testId'
      preLoaderRoute: typeof PracticeTestIdRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/mocks/$mockId': {
      id: '/mocks/$mockId'
      path: '/$mockId'
      fullPath: '/mocks/$mockId'
      preLoaderRoute: typeof MocksMockIdRouteImport
      parentRoute: typeof MocksRoute
    }
  }
}

interface MocksRouteChildren {
  MocksMockIdRoute: typeof MocksMockIdRoute
}

const MocksRouteChildren: MocksRouteChildren = {
  MocksMockIdRoute: MocksMockIdRoute,
}

const MocksRouteWithChildren = MocksRoute._addFileChildren(MocksRouteChildren)

interface PracticeRouteChildren {
  PracticeTestIdRoute: typeof PracticeTestIdRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeTestIdRoute: PracticeTestIdRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  LeaderboardRoute: LeaderboardRoute,
  MocksRoute: MocksRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
